"""create devis table

Revision ID: 6a49de41324d
Revises: 5556baf8a36f
Create Date: 2026-09-30 12:49:48.168555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a49de41324d'
down_revision: Union[str, Sequence[str], None] = '5556baf8a36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_devis', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('produit', sa.String(length=100), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_client_id'), 'devis', ['client_id'], unique=False)
    op.create_index(op.f('ix_devis_id'), 'devis', ['id'], unique=False)
    op.create_index(op.f('ix_devis_numero_devis'), 'devis', ['numero_devis'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devis_numero_devis'), table_name='devis')
    op.drop_index(op.f('ix_devis_id'), table_name='devis')
    op.drop_index(op.f('ix_devis_client_id'), table_name='devis')
    op.drop_table('devis')
    # ### end Alembic commands ###
