"""create produits table

Revision ID: 7c3489bf06a6
Revises: 9a4105edae7f
Create Date: 2026-10-04 21:03:51.350940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3489bf06a6'
down_revision: Union[str, Sequence[str], None] = '9a4105edae7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_produits_id'), 'produits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produits_id'), table_name='produits')
    op.drop_table('produits')
    # ### end Alembic commands ###
