"""create devis auto table

Revision ID: 7fce77c259d6
Revises: 7c3489bf06a6
Create Date: 2026-10-04 21:50:40.459189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fce77c259d6'
down_revision: Union[str, Sequence[str], None] = '7c3489bf06a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devis_auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=False),
    sa.Column('immatriculation', sa.String(length=30), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=True),
    sa.Column('puissance_fiscale', sa.Integer(), nullable=True),
    sa.Column('valeur_vehicule', sa.Float(), nullable=True),
    sa.Column('date_premiere_mise_circulation', sa.Date(), nullable=True),
    sa.Column('usage_vehicule', sa.String(length=100), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_auto_devis_id'), 'devis_auto', ['devis_id'], unique=True)
    op.create_index(op.f('ix_devis_auto_id'), 'devis_auto', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devis_auto_id'), table_name='devis_auto')
    op.drop_index(op.f('ix_devis_auto_devis_id'), table_name='devis_auto')
    op.drop_table('devis_auto')
    # ### end Alembic commands ###
