"""create contrats table

Revision ID: 9a4105edae7f
Revises: 6a49de41324d
Create Date: 2026-10-04 19:34:51.689297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4105edae7f'
down_revision: Union[str, Sequence[str], None] = '6a49de41324d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_contrat', sa.String(length=50), nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('produit', sa.String(length=100), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrats_client_id'), 'contrats', ['client_id'], unique=False)
    op.create_index(op.f('ix_contrats_devis_id'), 'contrats', ['devis_id'], unique=True)
    op.create_index(op.f('ix_contrats_id'), 'contrats', ['id'], unique=False)
    op.create_index(op.f('ix_contrats_numero_contrat'), 'contrats', ['numero_contrat'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contrats_numero_contrat'), table_name='contrats')
    op.drop_index(op.f('ix_contrats_id'), table_name='contrats')
    op.drop_index(op.f('ix_contrats_devis_id'), table_name='contrats')
    op.drop_index(op.f('ix_contrats_client_id'), table_name='contrats')
    op.drop_table('contrats')
    # ### end Alembic commands ###
